### ISSUE TITLE
Create python 2 and 3 environment and run SpatialKappa on both of them

### ISSUE THREAD

**Issue by rjwen2045458** [rjwen2045458/KappaNEURON#4]

**Comment by rjwen2045458** [comment]
@davidcsterratt

The python2 and python3 are both tested. The results turn out to be failed by same reason. All the tests report the same issue from either python2 and python3. 

Traceback (most recent call last):
  File "SpatialKappa/tests/__init__.py", line 11, in setUp
    self.sim = self.sk.kappa_sim("ms", True)
  File "SpatialKappa/__init__.py", line 145, in kappa_sim
    ks = self.gateway.jvm.org.demonsoft.spatialkappa.api.SpatialKappaSim(time_units, verbose, seed)
TypeError: 'JavaPackage' object is not callable 

The potential reason may be py4j version problems. I am trying to find out.

**Comment by davidcsterratt** [comment]
I wonder if the problem maybe the SpatialKappa jar file that you should find bundled in the SpatialKappa python package, and which is also in the SpatialKappa repository:
https://github.com/davidcsterratt/SpatialKappa/blob/master/SpatialKappa-v2.1.5.jar
https://github.com/davidcsterratt/SpatialKappa/blob/master/ant-antlr-3.2.jar

Does
```
java -jar SpatialKappa-v2.1.5.jar
```
from the command line work?

The jar files are referred to here:
https://github.com/davidcsterratt/SpatialKappa/blob/fd1395eb727c655313068ddd75392dce5199d662/python/SpatialKappa/__init__.py#L31

**Comment by rjwen2045458** [comment]
The installation of the python interface of SpatialKappa is fixed by creating directory "python/SpatialKappa/share/SpatialKappa", copying and pasting SpatialKappa-v2.1.5.jar and ant-antlr-3.2.jar into it. The python interfaces of SpatialKappa for python 2 and 3 can be installed through https://github.com/rjwen2045458/SpatialKappa/blob/master/python/INSTALL.md
The unittests tests are passed on both python2 and python3.
